# Site settings
title:          Swetha's Blog
description:    "My Blog with summaries of some research papers and cooking recipes."
baseurl:        ""
url:            "https://swethatanamala.github.io/"

# Author
author:
  name:              Swetha Tanamala
  url:               https://twitter.com/swetha_tanamala/
  email:             swetha.tanamala@gmail.com

# Build settings
markdown:       kramdown
mathjax: true

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
# permalink:      /:year-:month-:day/:title
permalink:     pretty
paginate:       5
